name: '${project.artifactId}'
version: '${project.version}'
main: it.fulminazzo.fulmichat.FulmiChat
api-version: 1.13
softdepend: [BearCommands, EssentialsChat, VentureChat, LPC]
authors: [Fulminazzo]
description: FulmiChat is a plugin that adds mentions, emojis and items in chat.

commands:
  moderate:
    description: A command to moderate a player.
    permission: fulmichat.mod
    aliases: [mod]
  emoji:
    description: A command to display all available emojis
    permission: fulmichat.emoji
    aliases: [emojis]